version: "3.8"
services:
    listener:
        build: 
            context: ../
            dockerfile: docker/uvicorn.Dockerfile
        container_name: listener
        environment:
            - GIT_URL=https://github.com/chrimaho/code-snippets.git
            - REPO_DIR=repo
            - VERSION=0.0.1
            - TITLE=Update from Git
            - DESCRIPTION=Automated update process for pulling from Git repo upon webhook call.
            - CONTACT_NAME=Chris Mahoney
            - CONTACT_URL=https://www.chrimaho.com
            - CONTACT_EMAIL=chrimaho@chrimaho.com
        volumes:
            - ../src:/app/src
            - ../repo:/app/repo
        ports:
            - 8880:8000
            - 443:8000
            - 80:80